language: python
cache: pip
dist: xenial
python:
  - "3.6"
# command to install dependencies
before_install:
  - sudo apt-get install -y antlr4
install:
  - pip install --upgrade pip
# command to run tests
before_script:
  - make
  - wget https://github.com/stan-dev/cmdstan/releases/download/v2.18.0/cmdstan-2.18.0.tar.gz
  - tar -xvfz cmdstan-2.18.0.tar.gz
  - cd cmdstan-2.18.0 && make build && cd ..
  - export CMDSTAN=`pwd`/'cmdstan-2.18.0'
  - pip install nose
  - pip install .
script:
  - make test